name: Initial setup to create KV and Storage of TF State

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  terraform:
    name: 'Intial Setup'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

      - name: Connect to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call a Bash Script
        env:
          TF_STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.strorageaccount }}       
        run:  bash ${GITHUB_WORKSPACE}/scripts/init-setup.sh